name: Kernel

on: push

jobs:
  build:
    name: My Job;
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Build Kernel
      run: |
        chmod a+x ./build.sh
        ./build.sh
      shell: bash
      env:
        TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }} 
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: cactus.zip
        path: AnyKernel
